const countries = [
  // AMÉRICA DO SUL — 12
  { code: "AR", name: "Argentina", continent: "south-america", flagFile: "ar.svg" },
  { code: "BO", name: "Bolívia", continent: "south-america", flagFile: "bo.svg" },
  { code: "BR", name: "Brasil", continent: "south-america", flagFile: "br.svg" },
  { code: "CL", name: "Chile", continent: "south-america", flagFile: "cl.svg" },
  { code: "CO", name: "Colômbia", continent: "south-america", flagFile: "co.svg" },
  { code: "EC", name: "Equador", continent: "south-america", flagFile: "ec.svg" },
  { code: "GY", name: "Guiana", continent: "south-america", flagFile: "gy.svg" },
  { code: "PY", name: "Paraguai", continent: "south-america", flagFile: "py.svg" },
  { code: "PE", name: "Peru", continent: "south-america", flagFile: "pe.svg" },
  { code: "SR", name: "Suriname", continent: "south-america", flagFile: "sr.svg" },
  { code: "UY", name: "Uruguai", continent: "south-america", flagFile: "uy.svg" },
  { code: "VE", name: "Venezuela", continent: "south-america", flagFile: "ve.svg" },

  // AMÉRICA DO NORTE, CENTRAL E CARIBE — 23
  { code: "AG", name: "Antígua e Barbuda", continent: "north-america", flagFile: "ag.svg" },
  { code: "BS", name: "Bahamas", continent: "north-america", flagFile: "bs.svg" },
  { code: "BB", name: "Barbados", continent: "north-america", flagFile: "bb.svg" },
  { code: "BZ", name: "Belize", continent: "north-america", flagFile: "bz.svg" },
  { code: "CA", name: "Canadá", continent: "north-america", flagFile: "ca.svg" },
  { code: "CR", name: "Costa Rica", continent: "north-america", flagFile: "cr.svg" },
  { code: "CU", name: "Cuba", continent: "north-america", flagFile: "cu.svg" },
  { code: "DM", name: "Dominica", continent: "north-america", flagFile: "dm.svg" },
  { code: "DO", name: "República Dominicana", continent: "north-america", flagFile: "do.svg" },
  { code: "SV", name: "El Salvador", continent: "north-america", flagFile: "sv.svg" },
  { code: "GD", name: "Granada", continent: "north-america", flagFile: "gd.svg" },
  { code: "GT", name: "Guatemala", continent: "north-america", flagFile: "gt.svg" },
  { code: "HT", name: "Haiti", continent: "north-america", flagFile: "ht.svg" },
  { code: "HN", name: "Honduras", continent: "north-america", flagFile: "hn.svg" },
  { code: "JM", name: "Jamaica", continent: "north-america", flagFile: "jm.svg" },
  { code: "MX", name: "México", continent: "north-america", flagFile: "mx.svg" },
  { code: "NI", name: "Nicarágua", continent: "north-america", flagFile: "ni.svg" },
  { code: "PA", name: "Panamá", continent: "north-america", flagFile: "pa.svg" },
  { code: "KN", name: "São Cristóvão e Névis", continent: "north-america", flagFile: "kn.svg" },
  { code: "LC", name: "Santa Lúcia", continent: "north-america", flagFile: "lc.svg" },
  { code: "VC", name: "São Vicente e Granadinas", continent: "north-america", flagFile: "vc.svg" },
  { code: "TT", name: "Trinidad e Tobago", continent: "north-america", flagFile: "tt.svg" },
  { code: "US", name: "Estados Unidos", continent: "north-america", flagFile: "us.svg" },

  // EUROPA — 44
  { code: "AL", name: "Albânia", continent: "europe", flagFile: "al.svg" },
  { code: "AD", name: "Andorra", continent: "europe", flagFile: "ad.svg" },
  { code: "AT", name: "Áustria", continent: "europe", flagFile: "at.svg" },
  { code: "BY", name: "Belarus", continent: "europe", flagFile: "by.svg" },
  { code: "BE", name: "Bélgica", continent: "europe", flagFile: "be.svg" },
  { code: "BA", name: "Bósnia e Herzegovina", continent: "europe", flagFile: "ba.svg" },
  { code: "BG", name: "Bulgária", continent: "europe", flagFile: "bg.svg" },
  { code: "HR", name: "Croácia", continent: "europe", flagFile: "hr.svg" },
  { code: "CZ", name: "Tchéquia", continent: "europe", flagFile: "cz.svg" },
  { code: "DK", name: "Dinamarca", continent: "europe", flagFile: "dk.svg" },
  { code: "EE", name: "Estônia", continent: "europe", flagFile: "ee.svg" },
  { code: "FI", name: "Finlândia", continent: "europe", flagFile: "fi.svg" },
  { code: "FR", name: "França", continent: "europe", flagFile: "fr.svg" },
  { code: "DE", name: "Alemanha", continent: "europe", flagFile: "de.svg" },
  { code: "GR", name: "Grécia", continent: "europe", flagFile: "gr.svg" },
  { code: "VA", name: "Vaticano", continent: "europe", flagFile: "va.svg" },
  { code: "HU", name: "Hungria", continent: "europe", flagFile: "hu.svg" },
  { code: "IS", name: "Islândia", continent: "europe", flagFile: "is.svg" },
  { code: "IE", name: "Irlanda", continent: "europe", flagFile: "ie.svg" },
  { code: "IT", name: "Itália", continent: "europe", flagFile: "it.svg" },
  { code: "LV", name: "Letônia", continent: "europe", flagFile: "lv.svg" },
  { code: "LI", name: "Liechtenstein", continent: "europe", flagFile: "li.svg" },
  { code: "LT", name: "Lituânia", continent: "europe", flagFile: "lt.svg" },
  { code: "LU", name: "Luxemburgo", continent: "europe", flagFile: "lu.svg" },
  { code: "MT", name: "Malta", continent: "europe", flagFile: "mt.svg" },
  { code: "MD", name: "Moldávia", continent: "europe", flagFile: "md.svg" },
  { code: "MC", name: "Mônaco", continent: "europe", flagFile: "mc.svg" },
  { code: "ME", name: "Montenegro", continent: "europe", flagFile: "me.svg" },
  { code: "NL", name: "Países Baixos", continent: "europe", flagFile: "nl.svg" },
  { code: "MK", name: "Macedônia do Norte", continent: "europe", flagFile: "mk.svg" },
  { code: "NO", name: "Noruega", continent: "europe", flagFile: "no.svg" },
  { code: "PL", name: "Polônia", continent: "europe", flagFile: "pl.svg" },
  { code: "PT", name: "Portugal", continent: "europe", flagFile: "pt.svg" },
  { code: "RO", name: "Romênia", continent: "europe", flagFile: "ro.svg" },
  { code: "RU", name: "Rússia", continent: "europe", flagFile: "ru.svg" },
  { code: "SM", name: "San Marino", continent: "europe", flagFile: "sm.svg" },
  { code: "RS", name: "Sérvia", continent: "europe", flagFile: "rs.svg" },
  { code: "SK", name: "Eslováquia", continent: "europe", flagFile: "sk.svg" },
  { code: "SI", name: "Eslovênia", continent: "europe", flagFile: "si.svg" },
  { code: "ES", name: "Espanha", continent: "europe", flagFile: "es.svg" },
  { code: "SE", name: "Suécia", continent: "europe", flagFile: "se.svg" },
  { code: "CH", name: "Suíça", continent: "europe", flagFile: "ch.svg" },
  { code: "UA", name: "Ucrânia", continent: "europe", flagFile: "ua.svg" },
  { code: "GB", name: "Reino Unido", continent: "europe", flagFile: "gb.svg" },
  // ÁFRICA — 54
  { code: "DZ", name: "Argélia", continent: "africa", flagFile: "dz.svg" },
  { code: "AO", name: "Angola", continent: "africa", flagFile: "ao.svg" },
  { code: "BJ", name: "Benim", continent: "africa", flagFile: "bj.svg" },
  { code: "BW", name: "Botsuana", continent: "africa", flagFile: "bw.svg" },
  { code: "BF", name: "Burkina Faso", continent: "africa", flagFile: "bf.svg" },
  { code: "BI", name: "Burundi", continent: "africa", flagFile: "bi.svg" },
  { code: "CV", name: "Cabo Verde", continent: "africa", flagFile: "cv.svg" },
  { code: "CM", name: "Camarões", continent: "africa", flagFile: "cm.svg" },
  { code: "CF", name: "República Centro-Africana", continent: "africa", flagFile: "cf.svg" },
  { code: "TD", name: "Chade", continent: "africa", flagFile: "td.svg" },
  { code: "KM", name: "Comores", continent: "africa", flagFile: "km.svg" },
  { code: "CG", name: "República do Congo", continent: "africa", flagFile: "cg.svg" },
  { code: "CD", name: "República Democrática do Congo", continent: "africa", flagFile: "cd.svg" },
  { code: "CI", name: "Costa do Marfim", continent: "africa", flagFile: "ci.svg" },
  { code: "DJ", name: "Djibuti", continent: "africa", flagFile: "dj.svg" },
  { code: "EG", name: "Egito", continent: "africa", flagFile: "eg.svg" },
  { code: "GQ", name: "Guiné Equatorial", continent: "africa", flagFile: "gq.svg" },
  { code: "ER", name: "Eritreia", continent: "africa", flagFile: "er.svg" },
  { code: "SZ", name: "Essuatíni", continent: "africa", flagFile: "sz.svg" },
  { code: "ET", name: "Etiópia", continent: "africa", flagFile: "et.svg" },
  { code: "GA", name: "Gabão", continent: "africa", flagFile: "ga.svg" },
  { code: "GM", name: "Gâmbia", continent: "africa", flagFile: "gm.svg" },
  { code: "GH", name: "Gana", continent: "africa", flagFile: "gh.svg" },
  { code: "GN", name: "Guiné", continent: "africa", flagFile: "gn.svg" },
  { code: "GW", name: "Guiné-Bissau", continent: "africa", flagFile: "gw.svg" },
  { code: "KE", name: "Quênia", continent: "africa", flagFile: "ke.svg" },
  { code: "LS", name: "Lesoto", continent: "africa", flagFile: "ls.svg" },
  { code: "LR", name: "Libéria", continent: "africa", flagFile: "lr.svg" },
  { code: "LY", name: "Líbia", continent: "africa", flagFile: "ly.svg" },
  { code: "MG", name: "Madagascar", continent: "africa", flagFile: "mg.svg" },
  { code: "MW", name: "Malawi", continent: "africa", flagFile: "mw.svg" },
  { code: "ML", name: "Mali", continent: "africa", flagFile: "ml.svg" },
  { code: "MR", name: "Mauritânia", continent: "africa", flagFile: "mr.svg" },
  { code: "MU", name: "Maurício", continent: "africa", flagFile: "mu.svg" },
  { code: "MA", name: "Marrocos", continent: "africa", flagFile: "ma.svg" },
  { code: "MZ", name: "Moçambique", continent: "africa", flagFile: "mz.svg" },
  { code: "NA", name: "Namíbia", continent: "africa", flagFile: "na.svg" },
  { code: "NE", name: "Níger", continent: "africa", flagFile: "ne.svg" },
  { code: "NG", name: "Nigéria", continent: "africa", flagFile: "ng.svg" },
  { code: "RW", name: "Ruanda", continent: "africa", flagFile: "rw.svg" },
  { code: "ST", name: "São Tomé e Príncipe", continent: "africa", flagFile: "st.svg" },
  { code: "SN", name: "Senegal", continent: "africa", flagFile: "sn.svg" },
  { code: "SC", name: "Seicheles", continent: "africa", flagFile: "sc.svg" },
  { code: "SL", name: "Serra Leoa", continent: "africa", flagFile: "sl.svg" },
  { code: "SO", name: "Somália", continent: "africa", flagFile: "so.svg" },
  { code: "ZA", name: "África do Sul", continent: "africa", flagFile: "za.svg" },
  { code: "SS", name: "Sudão do Sul", continent: "africa", flagFile: "ss.svg" },
  { code: "SD", name: "Sudão", continent: "africa", flagFile: "sd.svg" },
  { code: "TZ", name: "Tanzânia", continent: "africa", flagFile: "tz.svg" },
  { code: "TG", name: "Togo", continent: "africa", flagFile: "tg.svg" },
  { code: "TN", name: "Tunísia", continent: "africa", flagFile: "tn.svg" },
  { code: "UG", name: "Uganda", continent: "africa", flagFile: "ug.svg" },
  { code: "ZM", name: "Zâmbia", continent: "africa", flagFile: "zm.svg" },
  { code: "ZW", name: "Zimbábue", continent: "africa", flagFile: "zw.svg" },

  // ÁSIA — 48
  { code: "AF", name: "Afeganistão", continent: "asia", flagFile: "af.svg" },
  { code: "AM", name: "Armênia", continent: "asia", flagFile: "am.svg" },
  { code: "AZ", name: "Azerbaijão", continent: "asia", flagFile: "az.svg" },
  { code: "BH", name: "Bahrein", continent: "asia", flagFile: "bh.svg" },
  { code: "BD", name: "Bangladesh", continent: "asia", flagFile: "bd.svg" },
  { code: "BT", name: "Butão", continent: "asia", flagFile: "bt.svg" },
  { code: "BN", name: "Brunei", continent: "asia", flagFile: "bn.svg" },
  { code: "KH", name: "Camboja", continent: "asia", flagFile: "kh.svg" },
  { code: "CN", name: "China", continent: "asia", flagFile: "cn.svg" },
  { code: "CY", name: "Chipre", continent: "asia", flagFile: "cy.svg" },
  { code: "GE", name: "Geórgia", continent: "asia", flagFile: "ge.svg" },
  { code: "IN", name: "Índia", continent: "asia", flagFile: "in.svg" },
  { code: "ID", name: "Indonésia", continent: "asia", flagFile: "id.svg" },
  { code: "IR", name: "Irã", continent: "asia", flagFile: "ir.svg" },
  { code: "IQ", name: "Iraque", continent: "asia", flagFile: "iq.svg" },
  { code: "IL", name: "Israel", continent: "asia", flagFile: "il.svg" },
  { code: "JP", name: "Japão", continent: "asia", flagFile: "jp.svg" },
  { code: "JO", name: "Jordânia", continent: "asia", flagFile: "jo.svg" },
  { code: "KZ", name: "Cazaquistão", continent: "asia", flagFile: "kz.svg" },
  { code: "KW", name: "Kuwait", continent: "asia", flagFile: "kw.svg" },
  { code: "KG", name: "Quirguistão", continent: "asia", flagFile: "kg.svg" },
  { code: "LA", name: "Laos", continent: "asia", flagFile: "la.svg" },
  { code: "LB", name: "Líbano", continent: "asia", flagFile: "lb.svg" },
  { code: "MY", name: "Malásia", continent: "asia", flagFile: "my.svg" },
  { code: "MV", name: "Maldivas", continent: "asia", flagFile: "mv.svg" },
  { code: "MN", name: "Mongólia", continent: "asia", flagFile: "mn.svg" },
  { code: "MM", name: "Mianmar", continent: "asia", flagFile: "mm.svg" },
  { code: "NP", name: "Nepal", continent: "asia", flagFile: "np.svg" },
  { code: "KP", name: "Coreia do Norte", continent: "asia", flagFile: "kp.svg" },
  { code: "OM", name: "Omã", continent: "asia", flagFile: "om.svg" },
  { code: "PK", name: "Paquistão", continent: "asia", flagFile: "pk.svg" },
  { code: "PS", name: "Palestina", continent: "asia", flagFile: "ps.svg" },
  { code: "PH", name: "Filipinas", continent: "asia", flagFile: "ph.svg" },
  { code: "QA", name: "Catar", continent: "asia", flagFile: "qa.svg" },
  { code: "SA", name: "Arábia Saudita", continent: "asia", flagFile: "sa.svg" },
  { code: "SG", name: "Singapura", continent: "asia", flagFile: "sg.svg" },
  { code: "KR", name: "Coreia do Sul", continent: "asia", flagFile: "kr.svg" },
  { code: "LK", name: "Sri Lanka", continent: "asia", flagFile: "lk.svg" },
  { code: "SY", name: "Síria", continent: "asia", flagFile: "sy.svg" },
  { code: "TJ", name: "Tajiquistão", continent: "asia", flagFile: "tj.svg" },
  { code: "TH", name: "Tailândia", continent: "asia", flagFile: "th.svg" },
  { code: "TL", name: "Timor-Leste", continent: "asia", flagFile: "tl.svg" },
  { code: "TR", name: "Turquia", continent: "asia", flagFile: "tr.svg" },
  { code: "TM", name: "Turcomenistão", continent: "asia", flagFile: "tm.svg" },
  { code: "AE", name: "Emirados Árabes Unidos", continent: "asia", flagFile: "ae.svg" },
  { code: "UZ", name: "Uzbequistão", continent: "asia", flagFile: "uz.svg" },
  { code: "VN", name: "Vietnã", continent: "asia", flagFile: "vn.svg" },
  { code: "YE", name: "Iêmen", continent: "asia", flagFile: "ye.svg" },

  // OCEANIA — 14
  { code: "AU", name: "Austrália", continent: "oceania", flagFile: "au.svg" },
  { code: "FJ", name: "Fiji", continent: "oceania", flagFile: "fj.svg" },
  { code: "KI", name: "Kiribati", continent: "oceania", flagFile: "ki.svg" },
  { code: "MH", name: "Ilhas Marshall", continent: "oceania", flagFile: "mh.svg" },
  { code: "FM", name: "Micronésia", continent: "oceania", flagFile: "fm.svg" },
  { code: "NR", name: "Nauru", continent: "oceania", flagFile: "nr.svg" },
  { code: "NZ", name: "Nova Zelândia", continent: "oceania", flagFile: "nz.svg" },
  { code: "PW", name: "Palau", continent: "oceania", flagFile: "pw.svg" },
  { code: "PG", name: "Papua-Nova Guiné", continent: "oceania", flagFile: "pg.svg" },
  { code: "WS", name: "Samoa", continent: "oceania", flagFile: "ws.svg" },
  { code: "SB", name: "Ilhas Salomão", continent: "oceania", flagFile: "sb.svg" },
  { code: "TO", name: "Tonga", continent: "oceania", flagFile: "to.svg" },
  { code: "TV", name: "Tuvalu", continent: "oceania", flagFile: "tv.svg" },
  { code: "VU", name: "Vanuatu", continent: "oceania", flagFile: "vu.svg" }
];